## 数据加载

In [1]:
import tensorflow as tf

In [3]:
tf.__version__

'2.2.0'

In [4]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


True

In [5]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [6]:
## 列表数据 list

In [11]:
dataset = tf.data.Dataset.from_tensor_slices([[1, 2],[2, 3],[3,4]])

In [12]:
for i in dataset:
    print(i)

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)
tf.Tensor([3 4], shape=(2,), dtype=int32)


## generator生成器

In [24]:
def gen():
    for i in range(100):
        yield i, i*2

In [25]:
dataset = tf.data.Dataset.from_generator(gen,
                                        (tf.int64, tf.int64),
                                        (tf.TensorShape([]), tf.TensorShape([])))

In [26]:
list(dataset.take(10).as_numpy_iterator())

[(0, 0),
 (1, 2),
 (2, 4),
 (3, 6),
 (4, 8),
 (5, 10),
 (6, 12),
 (7, 14),
 (8, 16),
 (9, 18)]

In [19]:
# tf.TensorShape([]) 是什么意思？

## 文本文件tf.data.TextLineDataset()

In [27]:
import os

In [28]:
basedir = "./files"
files = ["train.txt", "dev.txt"]

In [29]:
def labeler(example, index):
    return example, tf.cast(index, tf.int64)

In [32]:
label_data_sets = []
for i, filename in enumerate(files):
    lines_dataset = tf.data.TextLineDataset(os.path.join(basedir, filename))
    labeled_dataset = lines_dataset.map(lambda x: labeler(x, i))
    label_data_sets.append(labeled_dataset)
    

In [33]:
for i in label_data_sets:
    print(i)

<MapDataset shapes: ((), ()), types: (tf.string, tf.int64)>
<MapDataset shapes: ((), ()), types: (tf.string, tf.int64)>
